name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/trophies.svg

      - name: Detailed Stats and Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }}
          user: Sahitya0805
          filename: assets/detailed_stats.svg
          base: activity, community
          base_indepth: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_only: pull-shark
          plugin_followup: yes
          plugin_followup_sections: user
          config_timezone: Asia/Kolkata
